from __future__ import (
    unicode_literals,
)
from scriptures.canons.base import (
    CanonBase,
)


class Canon(
    CanonBase
):
    """
    Protestant Canonical Bible with Old and New Testaments
    """

    name = "protestant"
    books = {
        "gen": {
            "en": (
                "Genesis",
                "Gen.",
                "Ge.",
                "Gn.",
                "Gen",
                "Gen(?:esis)?",
            ),
            "chapters": [
                31,
                25,
                24,
                26,
                32,
                22,
                24,
                22,
                29,
                32,
                32,
                20,
                18,
                24,
                21,
                16,
                27,
                33,
                38,
                18,
                34,
                24,
                20,
                67,
                34,
                35,
                46,
                22,
                35,
                43,
                55,
                32,
                20,
                31,
                29,
                43,
                36,
                30,
                23,
                23,
                57,
                38,
                34,
                34,
                28,
                34,
                31,
                22,
                33,
                26,
            ],
        },
        "exod": {
            "en": (
                "Exodus",
                "Ex.",
                "Exod.",
                "Exo.",
                "Exod",
                "Exod(?:us)?",
            ),
            "chapters": [
                22,
                25,
                22,
                31,
                23,
                30,
                25,
                32,
                35,
                29,
                10,
                51,
                22,
                31,
                27,
                36,
                16,
                27,
                25,
                26,
                36,
                31,
                33,
                18,
                40,
                37,
                21,
                43,
                46,
                38,
                18,
                35,
                23,
                35,
                35,
                38,
                29,
                31,
                43,
                38,
            ],
        },
        "lev": {
            "en": (
                "Leviticus",
                "Lev.",
                "Le.",
                "Lv.",
                "Lev",
                "Lev(?:iticus)?",
            ),
            "chapters": [
                17,
                16,
                17,
                35,
                19,
                30,
                38,
                36,
                24,
                20,
                47,
                8,
                59,
                57,
                33,
                34,
                16,
                30,
                37,
                27,
                24,
                33,
                44,
                23,
                55,
                46,
                34,
            ],
        },
        "num": {
            "en": (
                "Numbers",
                "Num.",
                "Nu.",
                "Nm.",
                "Nb.",
                "Num",
                "Num(?:bers)?",
            ),
            "chapters": [
                54,
                34,
                51,
                49,
                31,
                27,
                89,
                26,
                23,
                36,
                35,
                16,
                33,
                45,
                41,
                50,
                13,
                32,
                22,
                29,
                35,
                41,
                30,
                25,
                18,
                65,
                23,
                31,
                40,
                16,
                54,
                42,
                56,
                29,
                34,
                13,
            ],
        },
        "deut": {
            "en": (
                "Deuteronomy",
                "Deut.",
                "De.",
                "Dt.",
                "Deut",
                "Deut(?:eronomy)?",
            ),
            "chapters": [
                46,
                37,
                29,
                49,
                33,
                25,
                26,
                20,
                29,
                22,
                32,
                32,
                18,
                29,
                23,
                22,
                20,
                22,
                21,
                20,
                23,
                30,
                25,
                22,
                19,
                19,
                26,
                68,
                29,
                20,
                30,
                52,
                29,
                12,
            ],
        },
        "josh": {
            "en": (
                "Joshua",
                "Josh.",
                "Jos.",
                "Jsh.",
                "Josh",
                "Josh(?:ua)?",
            ),
            "chapters": [
                18,
                24,
                17,
                24,
                15,
                27,
                26,
                35,
                27,
                43,
                23,
                24,
                33,
                15,
                63,
                10,
                18,
                28,
                51,
                9,
                45,
                34,
                16,
                33,
            ],
        },
        "judg": {
            "en": (
                "Judges",
                "Judg.",
                "Jdg.",
                "Jg.",
                "Jdgs.",
                "Judg",
                "Judg(?:es)?",
            ),
            "chapters": [
                36,
                23,
                31,
                24,
                31,
                40,
                25,
                35,
                57,
                18,
                40,
                15,
                25,
                20,
                20,
                31,
                13,
                31,
                30,
                48,
                25,
            ],
        },
        "ruth": {
            "en": (
                "Ruth",
                "Rth.",
                "Ru.",
            ),
            "chapters": [
                22,
                23,
                18,
                22,
            ],
        },
        "1sam": {
            "en": (
                "1 Samuel",
                "1 Sam.",
                "1 Sm.",
                "1 Sa.",
                "1 S.",
                "I Sam.",
                "I Sa.",
                "1Sam.",
                "1Sa.",
                "1S.",
                "1st Samuel",
                "1st Sam.",
                "First Samuel",
                "First Sam.",
                "I Samuel",
                "1Sam",
                "(?:1|I)(?:\s)?Sam(?:uel)?",
            ),
            "chapters": [
                28,
                36,
                21,
                22,
                12,
                21,
                17,
                22,
                27,
                27,
                15,
                25,
                23,
                52,
                35,
                23,
                58,
                30,
                24,
                42,
                15,
                23,
                29,
                22,
                44,
                25,
                12,
                25,
                11,
                31,
                13,
            ],
        },
        "2sam": {
            "en": (
                "2 Samuel",
                "2 Sam.",
                "2 Sm.",
                "2 Sa.",
                "2 S.",
                "II Sam.",
                "II Sa.",
                "2Sam.",
                "2Sa.",
                "2S.",
                "2nd Samuel",
                "2nd Sam.",
                "Second Samuel",
                "Second Sam.",
                "II Samuel",
                "2Sam",
                "(?:2|II)(?:\s)?Sam(?:uel)?",
            ),
            "chapters": [
                27,
                32,
                39,
                12,
                25,
                23,
                29,
                18,
                13,
                19,
                27,
                31,
                39,
                33,
                37,
                23,
                29,
                33,
                43,
                26,
                22,
                51,
                39,
                25,
            ],
        },
        "1kgs": {
            "en": (
                "1 Kings",
                "1 Kgs",
                "1 Ki",
                "1Kgs",
                "1Kin",
                "1Ki",
                "1K",
                "I Kgs",
                "I Ki",
                "1st Kings",
                "1st Kgs",
                "First Kings",
                "First Kgs",
                "I Kings",
                "(?:1|I)(?:\s)?K(?:in)?gs",
            ),
            "chapters": [
                53,
                46,
                28,
                34,
                18,
                38,
                51,
                66,
                28,
                29,
                43,
                33,
                34,
                31,
                34,
                34,
                24,
                46,
                21,
                43,
                29,
                53,
            ],
        },
        "2kgs": {
            "en": (
                "2 Kings",
                "2 Kgs.",
                "2 Ki.",
                "2Kgs.",
                "2Kin.",
                "2Ki.",
                "2K.",
                "II Kgs.",
                "II Ki.",
                "2nd Kings",
                "2nd Kgs.",
                "Second Kings",
                "Second Kgs.",
                "II Kings",
                "2Kgs",
                "(?:2|II)(?:\s)?K(?:in)?gs",
            ),
            "chapters": [
                18,
                25,
                27,
                44,
                27,
                33,
                20,
                29,
                37,
                36,
                21,
                21,
                25,
                29,
                38,
                20,
                41,
                37,
                37,
                21,
                26,
                20,
                37,
                20,
                30,
            ],
        },
        "1chr": {
            "en": (
                "1 Chronicles",
                "1 Chron.",
                "1 Chr.",
                "1 Ch.",
                "1Chron.",
                "1Chr.",
                "1Ch.",
                "I Chron.",
                "I Chr.",
                "I Ch.",
                "1st Chronicles",
                "1st Chron.",
                "First Chronicles",
                "First Chron.",
                "I Chronicles",
                "1Chr",
                "(?:1|I)(?:\s)?Chr(?:o(?:n(?:icles)?)?)?",
            ),
            "chapters": [
                54,
                55,
                24,
                43,
                26,
                81,
                40,
                40,
                44,
                14,
                47,
                40,
                14,
                17,
                29,
                43,
                27,
                17,
                19,
                8,
                30,
                19,
                32,
                31,
                31,
                32,
                34,
                21,
                30,
            ],
        },
        "2chr": {
            "en": (
                "2 Chronicles",
                "2 Chron.",
                "2 Chr.",
                "2 Ch.",
                "2Chron.",
                "2Chr.",
                "2Ch.",
                "II Chron.",
                "II Chr.",
                "II Ch.",
                "2nd Chronicles",
                "2nd Chron.",
                "Second Chronicles",
                "Second Chron.",
                "II Chronicles",
                "2Chr",
                "(?:2|II)(?:\s)?Chr(?:o(?:n(?:icles)?)?)?",
            ),
            "chapters": [
                17,
                18,
                17,
                22,
                14,
                42,
                22,
                18,
                31,
                19,
                23,
                16,
                22,
                15,
                19,
                14,
                19,
                34,
                11,
                37,
                20,
                12,
                21,
                27,
                28,
                23,
                9,
                27,
                36,
                27,
                21,
                33,
                25,
                33,
                27,
                23,
            ],
        },
        "ezra": {
            "en": (
                "Ezra",
                "Ezr.",
                "Ez.",
            ),
            "chapters": [
                11,
                70,
                13,
                24,
                17,
                22,
                28,
                36,
                15,
                44,
            ],
        },
        "neh": {
            "en": (
                "Nehemiah",
                "Neh.",
                "Ne.",
                "Neh",
                "Neh(?:emiah)?",
            ),
            "chapters": [
                11,
                20,
                32,
                23,
                19,
                19,
                73,
                18,
                38,
                39,
                36,
                47,
                31,
            ],
        },
        "esth": {
            "en": (
                "Esther",
                "Est.",
                "Esth.",
                "Es.",
                "Esth",
                "Esth(?:er)?",
            ),
            "chapters": [
                22,
                23,
                15,
                17,
                14,
                14,
                10,
                17,
                32,
                3,
            ],
        },
        "job": {
            "en": (
                "Job",
                "Jb.",
            ),
            "chapters": [
                22,
                13,
                26,
                21,
                27,
                30,
                21,
                22,
                35,
                22,
                20,
                25,
                28,
                22,
                35,
                22,
                16,
                21,
                29,
                29,
                34,
                30,
                17,
                25,
                6,
                14,
                23,
                28,
                25,
                31,
                40,
                22,
                33,
                37,
                16,
                33,
                24,
                41,
                30,
                24,
                34,
                17,
            ],
        },
        "ps": {
            "en": (
                "Psalms",
                "Ps.",
                "Psalm",
                "Pslm.",
                "Psa.",
                "Psm.",
                "Pss.",
                "Ps",
                "Ps(?:a)?(?:lm(?:s)?)?",
            ),
            "chapters": [
                6,
                12,
                8,
                8,
                12,
                10,
                17,
                9,
                20,
                18,
                7,
                8,
                6,
                7,
                5,
                11,
                15,
                50,
                14,
                9,
                13,
                31,
                6,
                10,
                22,
                12,
                14,
                9,
                11,
                12,
                24,
                11,
                22,
                22,
                28,
                12,
                40,
                22,
                13,
                17,
                13,
                11,
                5,
                26,
                17,
                11,
                9,
                14,
                20,
                23,
                19,
                9,
                6,
                7,
                23,
                13,
                11,
                11,
                17,
                12,
                8,
                12,
                11,
                10,
                13,
                20,
                7,
                35,
                36,
                5,
                24,
                20,
                28,
                23,
                10,
                12,
                20,
                72,
                13,
                19,
                16,
                8,
                18,
                12,
                13,
                17,
                7,
                18,
                52,
                17,
                16,
                15,
                5,
                23,
                11,
                13,
                12,
                9,
                9,
                5,
                8,
                28,
                22,
                35,
                45,
                48,
                43,
                13,
                31,
                7,
                10,
                10,
                9,
                8,
                18,
                19,
                2,
                29,
                176,
                7,
                8,
                9,
                4,
                8,
                5,
                6,
                5,
                6,
                8,
                8,
                3,
                18,
                3,
                3,
                21,
                26,
                9,
                8,
                24,
                13,
                10,
                7,
                12,
                15,
                21,
                10,
                20,
                14,
                9,
                6,
            ],
        },
        "prov": {
            "en": (
                "Proverbs",
                "Prov",
                "Pro.",
                "Prv.",
                "Pr.",
                "Prov(?:erbs)?",
            ),
            "chapters": [
                33,
                22,
                35,
                27,
                23,
                35,
                27,
                36,
                18,
                32,
                31,
                28,
                25,
                35,
                33,
                33,
                28,
                24,
                29,
                30,
                31,
                29,
                35,
                34,
                28,
                28,
                27,
                28,
                27,
                33,
                31,
            ],
        },
        "eccl": {
            "en": (
                "Ecclesiastes",
                "Eccles.",
                "Eccle.",
                "Ecc.",
                "Ec.",
                "Qoh.",
                "Eccl",
                "Ecc(?:l(?:es(?:iastes)?)?)?",
            ),
            "chapters": [
                18,
                26,
                22,
                16,
                20,
                12,
                29,
                17,
                18,
                20,
                10,
                14,
            ],
        },
        "song": {
            "en": (
                "Song of Solomon",
                "Song",
                "Song of Songs",
                "SOS.",
                "So.",
                "Canticle of Canticles",
                "Canticles",
                "Cant.",
                "Song(?: of Sol(?:omon)?)?",
            ),
            "chapters": [
                17,
                17,
                11,
                16,
                16,
                13,
                13,
                14,
            ],
        },
        "isa": {
            "en": (
                "Isaiah",
                "Isa.",
                "Is.",
                "Isa",
                "Isa(?:iah)?",
            ),
            "chapters": [
                31,
                22,
                26,
                6,
                30,
                13,
                25,
                22,
                21,
                34,
                16,
                6,
                22,
                32,
                9,
                14,
                14,
                7,
                25,
                6,
                17,
                25,
                18,
                23,
                12,
                21,
                13,
                29,
                24,
                33,
                9,
                20,
                24,
                17,
                10,
                22,
                38,
                22,
                8,
                31,
                29,
                25,
                28,
                28,
                25,
                13,
                15,
                22,
                26,
                11,
                23,
                15,
                12,
                17,
                13,
                12,
                21,
                14,
                21,
                22,
                11,
                12,
                19,
                12,
                25,
                24,
            ],
        },
        "jer": {
            "en": (
                "Jeremiah",
                "Jer.",
                "Je.",
                "Jr.",
                "Jer",
                "Jer(?:emiah)?",
            ),
            "chapters": [
                19,
                37,
                25,
                31,
                31,
                30,
                34,
                22,
                26,
                25,
                23,
                17,
                27,
                22,
                21,
                21,
                27,
                23,
                15,
                18,
                14,
                30,
                40,
                10,
                38,
                24,
                22,
                17,
                32,
                24,
                40,
                44,
                26,
                22,
                19,
                32,
                21,
                28,
                18,
                16,
                18,
                22,
                13,
                30,
                5,
                28,
                7,
                47,
                39,
                46,
                64,
                34,
            ],
        },
        "lam": {
            "en": (
                "Lamentations",
                "Lam.",
                "La.",
                "Lam",
                "Lam(?:entations)?",
            ),
            "chapters": [
                22,
                22,
                66,
                22,
                22,
            ],
        },
        "ezek": {
            "en": (
                "Ezekiel",
                "Ezek.",
                "Eze.",
                "Ezk.",
                "Ezek",
                "Ezek(?:iel)?",
            ),
            "chapters": [
                28,
                10,
                27,
                17,
                17,
                14,
                27,
                18,
                11,
                22,
                25,
                28,
                23,
                23,
                8,
                63,
                24,
                32,
                14,
                49,
                32,
                31,
                49,
                27,
                17,
                21,
                36,
                26,
                21,
                26,
                18,
                32,
                33,
                31,
                15,
                38,
                28,
                23,
                29,
                49,
                26,
                20,
                27,
                31,
                25,
                24,
                23,
                35,
            ],
        },
        "dan": {
            "en": (
                "Daniel",
                "Dan.",
                "Da.",
                "Dn.",
                "Dan",
                "Dan(?:iel)?",
            ),
            "chapters": [
                21,
                49,
                30,
                37,
                31,
                28,
                28,
                27,
                27,
                21,
                45,
                13,
            ],
        },
        "hos": {
            "en": (
                "Hosea",
                "Hos.",
                "Ho.",
                "Hos",
                "Hos(?:ea)?",
            ),
            "chapters": [
                11,
                23,
                5,
                19,
                15,
                11,
                16,
                14,
                17,
                15,
                12,
                14,
                16,
                9,
            ],
        },
        "joel": {
            "en": (
                "Joel",
                "Jl.",
            ),
            "chapters": [
                20,
                32,
                21,
            ],
        },
        "amos": {
            "en": (
                "Amos",
                "Am.",
            ),
            "chapters": [
                15,
                16,
                15,
                13,
                27,
                14,
                17,
                14,
                15,
            ],
        },
        "obad": {
            "en": (
                "Obadiah",
                "Obad.",
                "Ob.",
                "Obad",
                "Obad(?:iah)?",
            ),
            "chapters": [
                21
            ],
        },
        "jonah": {
            "en": (
                "Jonah",
                "Jnh.",
                "Jon.",
                "Jon(?:ah)?",
            ),
            "chapters": [
                17,
                10,
                10,
                11,
            ],
        },
        "mic": {
            "en": (
                "Micah",
                "Mic.",
                "Mc.",
                "Mic",
                "Mic(?:ah)?",
            ),
            "chapters": [
                16,
                13,
                12,
                13,
                15,
                16,
                20,
            ],
        },
        "nah": {
            "en": (
                "Nahum",
                "Nah.",
                "Na.",
                "Nah",
                "Nah(?:um)?",
            ),
            "chapters": [
                15,
                13,
                19,
            ],
        },
        "hab": {
            "en": (
                "Habakkuk",
                "Hab.",
                "Hb.",
                "Hab",
                "Hab(?:akkuk)?",
            ),
            "chapters": [
                17,
                20,
                19,
            ],
        },
        "zeph": {
            "en": (
                "Zephaniah",
                "Zeph.",
                "Zep.",
                "Zp.",
                "Zeph",
                "Zeph(?:aniah)?",
            ),
            "chapters": [
                18,
                15,
                20,
            ],
        },
        "hag": {
            "en": (
                "Haggai",
                "Hag.",
                "Hg.",
                "Hag",
                "Hag(?:gai)?",
            ),
            "chapters": [
                15,
                23,
            ],
        },
        "zech": {
            "en": (
                "Zechariah",
                "Zech.",
                "Zec.",
                "Zc.",
                "Zech",
                "Zech(?:ariah)?",
            ),
            "chapters": [
                21,
                13,
                10,
                14,
                11,
                15,
                14,
                23,
                17,
                12,
                17,
                14,
                9,
                21,
            ],
        },
        "mal": {
            "en": (
                "Malachi",
                "Mal.",
                "Ml.",
                "Mal",
                "Mal(?:achi)?",
            ),
            "chapters": [
                14,
                17,
                18,
                6,
            ],
        },
        "matt": {
            "en": (
                "Matthew",
                "Matt.",
                "Mt.",
                "Matt",
                "Matt(?:hew)?",
            ),
            "chapters": [
                25,
                23,
                17,
                25,
                48,
                34,
                29,
                34,
                38,
                42,
                30,
                50,
                58,
                36,
                39,
                28,
                27,
                35,
                30,
                34,
                46,
                46,
                39,
                51,
                46,
                75,
                66,
                20,
            ],
        },
        "mark": {
            "en": (
                "Mark",
                "Mrk",
                "Mar",
                "Mk",
                "Mr",
            ),
            "chapters": [
                45,
                28,
                35,
                41,
                43,
                56,
                37,
                38,
                50,
                52,
                33,
                44,
                37,
                72,
                47,
                20,
            ],
        },
        "luke": {
            "en": (
                "Luke",
                "Luk",
                "Lk",
            ),
            "chapters": [
                80,
                52,
                38,
                44,
                39,
                49,
                50,
                56,
                62,
                42,
                54,
                59,
                35,
                35,
                32,
                31,
                37,
                43,
                48,
                47,
                38,
                71,
                56,
                53,
            ],
        },
        "john": {
            "en": (
                "John",
                "Joh",
                "Jhn",
                "Jn",
                "(?<!(?:1|2|3|I)\s)(?<!(?:1|2|3|I))John",
            ),
            "chapters": [
                51,
                25,
                36,
                54,
                47,
                71,
                53,
                59,
                41,
                42,
                57,
                50,
                38,
                31,
                27,
                33,
                26,
                40,
                42,
                31,
                25,
            ],
        },
        "acts": {
            "en": (
                "Acts",
                "Act",
                "Ac",
            ),
            "chapters": [
                26,
                47,
                26,
                37,
                42,
                15,
                60,
                40,
                43,
                48,
                30,
                25,
                52,
                28,
                41,
                40,
                34,
                28,
                41,
                38,
                40,
                30,
                35,
                27,
                27,
                32,
                44,
                31,
            ],
        },
        "rom": {
            "en": (
                "Romans",
                "Rom.",
                "Ro.",
                "Rm.",
                "Rom",
                "Rom(?:ans)?",
            ),
            "chapters": [
                32,
                29,
                31,
                25,
                21,
                23,
                25,
                39,
                33,
                21,
                36,
                21,
                14,
                23,
                33,
                27,
            ],
        },
        "1cor": {
            "en": (
                "1 Corinthians",
                "1 Cor.",
                "1 Co.",
                "I Cor.",
                "I Co.",
                "1Cor.",
                "1Co.",
                "I Corinthians",
                "1Corinthians",
                "1st Corinthians",
                "2nd Corinthians",
                "1Cor",
                "(?:1|I)(?:\s)?Cor(?:inthians)?",
            ),
            "chapters": [
                31,
                16,
                23,
                21,
                13,
                20,
                40,
                13,
                27,
                33,
                34,
                31,
                13,
                40,
                58,
                24,
            ],
        },
        "2cor": {
            "en": (
                "2 Corinthians",
                "2 Cor.",
                "2 Co.",
                "II Cor.",
                "II Co.",
                "2Cor.",
                "2Co.",
                "II Corinthians",
                "2Corinthians",
                "2nd Corinthians",
                "Second Corinthians",
                "2Cor",
                "(?:2|II)(?:\s)?Cor(?:inthians)?",
            ),
            "chapters": [
                24,
                17,
                18,
                18,
                21,
                18,
                16,
                24,
                15,
                18,
                33,
                21,
                14,
            ],
        },
        "gal": {
            "en": (
                "Galatians",
                "Gal.",
                "Ga.",
                "Gal",
                "Gal(?:atians)?",
            ),
            "chapters": [
                24,
                21,
                29,
                31,
                26,
                18,
            ],
        },
        "eph": {
            "en": (
                "Ephesians",
                "Eph.",
                "Ephes.",
                "Eph",
                "Eph(?:esians)?",
            ),
            "chapters": [
                23,
                22,
                21,
                32,
                33,
                24,
            ],
        },
        "phil": {
            "en": (
                "Philippians",
                "Phil.",
                "Php.",
                "Pp.",
                "Phil",
                "Phil(?:ippians)?",
            ),
            "chapters": [
                30,
                30,
                21,
                23,
            ],
        },
        "col": {
            "en": (
                "Colossians",
                "Col.",
                "Co.",
                "Col",
                "Col(?:ossians)?",
            ),
            "chapters": [
                29,
                23,
                25,
                18,
            ],
        },
        "1thess": {
            "en": (
                "1 Thessalonians",
                "1 Thess.",
                "1 Thes.",
                "1 Th.",
                "I Thessalonians",
                "I Thess.",
                "I Thes.",
                "I Th.",
                "1Thessalonians",
                "1Thess.",
                "1Thes.",
                "1Th.",
                "1st Thessalonians",
                "1st Thess.",
                "First Thessalonians",
                "First Thess.",
                "1Thess",
                "(?:1|I)(?:\s)?Thess(?:alonians)?",
            ),
            "chapters": [
                10,
                20,
                13,
                18,
                28,
            ],
        },
        "2thess": {
            "en": (
                "2 Thessalonians",
                "2 Thess.",
                "2 Thes.",
                "II Thessalonians",
                "II Thess.",
                "II Thes.",
                "II Th.",
                "2Thessalonians",
                "2Thess.",
                "2Thes.",
                "2Th.",
                "2nd Thessalonians",
                "2nd Thess.",
                "Second Thessalonians",
                "Second Thess.",
                "2Thess",
                "(?:2|II)(?:\s)?Thess(?:alonians)?",
            ),
            "chapters": [
                12,
                17,
                18,
            ],
        },
        "1tim": {
            "en": (
                "1 Timothy",
                "1 Tim.",
                "1 Ti.",
                "I Timothy",
                "I Tim.",
                "I Ti.",
                "1Timothy",
                "1Tim.",
                "1Ti.",
                "1st Timothy",
                "1st Tim.",
                "First Timothy",
                "First Tim.",
                "1Tim",
                "(?:1|I)(?:\s)?Tim(?:othy)?",
            ),
            "chapters": [
                20,
                15,
                16,
                16,
                25,
                21,
            ],
        },
        "2tim": {
            "en": (
                "2 Timothy",
                "2 Tim.",
                "2 Ti.",
                "II Timothy",
                "II Tim.",
                "II Ti.",
                "2Timothy",
                "2Tim.",
                "2Ti.",
                "2nd Timothy",
                "2nd Tim.",
                "Second Timothy",
                "Second Tim.",
                "2Tim",
                "(?:2|II)(?:\s)?Tim(?:othy)?",
            ),
            "chapters": [
                18,
                26,
                17,
                22,
            ],
        },
        "titus": {
            "en": (
                "Titus",
                "Tit",
                "ti",
                "Tit(?:us)?",
            ),
            "chapters": [
                16,
                15,
                15,
            ],
        },
        "phlm": {
            "en": (
                "Philemon",
                "Philem.",
                "Phm.",
                "Pm.",
                "Phlm",
                "Phlm|Phile(?:m(?:on)?)?",
            ),
            "chapters": [
                25
            ],
        },
        "heb": {
            "en": (
                "Hebrews",
                "Heb.",
                "Heb",
                "Heb(?:rews)?",
            ),
            "chapters": [
                14,
                18,
                19,
                16,
                14,
                20,
                28,
                13,
                28,
                39,
                40,
                29,
                25,
            ],
        },
        "jas": {
            "en": (
                "James",
                "Jas",
                "Jm",
                "Ja(?:me)?s",
            ),
            "chapters": [
                27,
                26,
                18,
                17,
                20,
            ],
        },
        "1pet": {
            "en": (
                "1 Peter",
                "1 Pet.",
                "1 Pe.",
                "1 Pt.",
                "1 P.",
                "I Pet.",
                "I Pt.",
                "I Pe.",
                "1Peter",
                "1Pet.",
                "1Pe.",
                "1Pt.",
                "1P.",
                "I Peter",
                "1st Peter",
                "First Peter",
                "1Pet",
                "(?:1|I)(?:\s)?Pet(?:er)?",
            ),
            "chapters": [
                25,
                25,
                22,
                19,
                14,
            ],
        },
        "2pet": {
            "en": (
                "2 Peter",
                "2 Pet.",
                "2 Pe.",
                "2 Pt.",
                "2 P.",
                "II Peter",
                "II Pet.",
                "II Pt.",
                "II Pe.",
                "2Peter",
                "2Pet.",
                "2Pe.",
                "2Pt.",
                "2P.",
                "2nd Peter",
                "Second Peter",
                "2Pet",
                "(?:2|II)(?:\s)?Pet(?:er)?",
            ),
            "chapters": [
                21,
                22,
                18,
            ],
        },
        "1john": {
            "en": (
                "1 John",
                "1 Jhn.",
                "1 Jn.",
                "1 J.",
                "1John",
                "1Jhn.",
                "1Joh.",
                "1Jn.",
                "1Jo.",
                "1J.",
                "I John",
                "I Jhn.",
                "I Joh.",
                "I Jn.",
                "I Jo.",
                "1st John",
                "First John",
                "(?:(?:1|I)(?:\s)?)John",
            ),
            "chapters": [
                10,
                29,
                24,
                21,
                21,
            ],
        },
        "2john": {
            "en": (
                "2 John",
                "2 Jhn.",
                "2 Jn.",
                "2 J.",
                "2John",
                "2Jhn.",
                "2Joh.",
                "2Jn.",
                "2Jo.",
                "2J.",
                "II John",
                "II Jhn.",
                "II Joh.",
                "II Jn.",
                "II Jo.",
                "2nd John",
                "Second John",
                "(?:(?:2|II)(?:\s)?)John",
            ),
            "chapters": [
                13
            ],
        },
        "3john": {
            "en": (
                "3 John",
                "3 Jhn.",
                "3 Jn.",
                "3 J.",
                "3John",
                "3Jhn.",
                "3Joh.",
                "3Jn.",
                "3Jo.",
                "3J.",
                "III John",
                "III Jhn.",
                "III Joh.",
                "III Jn.",
                "III Jo.",
                "3rd John",
                "Third John",
                "(?:(?:3|III)(?:\s)?)John",
            ),
            "chapters": [
                14
            ],
        },
        "jude": {
            "en": (
                "Jude",
                "Jud.",
                "Jd.",
            ),
            "chapters": [
                25
            ],
        },
        "rev": {
            "en": (
                "Revelation",
                "Rev",
                "Re",
                "The Revelation",
                "Revelation of Jesus Christ",
                "Rev(?:elation)?(?:\sof Jesus Christ)?",
            ),
            "chapters": [
                20,
                29,
                22,
                11,
                14,
                17,
                17,
                13,
                21,
                11,
                19,
                17,
                18,
                20,
                8,
                21,
                18,
                24,
                21,
                15,
                27,
                21,
            ],
        },
    }
